// PROJECT 6: ENTERPRISE RETAIL DATA WAREHOUSE
// SNOWFLAKE SCHEMA DESIGN


// PHASE 1: SETUP


CREATE OR REPLACE WAREHOUSE PROJECT6_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE PROJECT6_WH;

CREATE OR REPLACE DATABASE RETAIL_SNOWFLAKE_DW;

USE DATABASE RETAIL_SNOWFLAKE_DW;

CREATE OR REPLACE SCHEMA STAGING;

CREATE OR REPLACE SCHEMA ANALYTICS;


// PHASE 2: CREATE STAGING TABLES

USE SCHEMA STAGING;


// Task 1: Create Customers Staging Table

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);


// Task 2: Create Products Staging Table

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);


// Task 3: Create Branches Staging Table

CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR(150),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);


// Task 4: Create Calendar Staging Table

CREATE OR REPLACE TABLE CALENDAR (
    DATE_ID NUMBER,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER,
    IS_WEEKEND VARCHAR(10)
);


// Task 5: Create Sales Staging Table

CREATE OR REPLACE TABLE SALES (
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2)
);


// PHASE 3: CREATE CSV FILE FORMAT

// Task 6: Create CSV File Format

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '');


// PHASE 4: CREATE STAGE

// Task 7: Create Internal Stage

CREATE OR REPLACE STAGE RETAIL_CSV_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @RETAIL_CSV_STAGE;


// PHASE 5: CHECK CSV FILES

// Task 8: Check Uploaded CSV Files

LIST @RETAIL_CSV_STAGE;


// PHASE 6: LOAD CSV FILES INTO STAGING TABLES

// Task 9: Load Customers

COPY INTO CUSTOMERS
FROM @RETAIL_CSV_STAGE
FILES = ('customers.csv')
FILE_FORMAT = CSV_FORMAT;


// Task 10: Load Products

COPY INTO PRODUCTS
FROM @RETAIL_CSV_STAGE
FILES = ('products.csv')
FILE_FORMAT = CSV_FORMAT;


// Task 11: Load Branches

COPY INTO BRANCHES
FROM @RETAIL_CSV_STAGE
FILES = ('branches.csv')
FILE_FORMAT = CSV_FORMAT;


// Task 12: Load Calendar

COPY INTO CALENDAR
FROM @RETAIL_CSV_STAGE
FILES = ('calendar.csv')
FILE_FORMAT = CSV_FORMAT;


// Task 13: Load Sales

COPY INTO SALES
FROM @RETAIL_CSV_STAGE
FILES = ('sales.csv')
FILE_FORMAT = CSV_FORMAT; 


// PHASE 7: VERIFY STAGING DATA

// Task 14: Display Customers

SELECT *
FROM CUSTOMERS
ORDER BY CUSTOMER_ID;


// Task 15: Display Products

SELECT *
FROM PRODUCTS
ORDER BY PRODUCT_ID;


// Task 16: Display Branches

SELECT *
FROM BRANCHES
ORDER BY BRANCH_ID;


// Task 17: Display Calendar

SELECT *
FROM CALENDAR
ORDER BY DATE_ID;


// Task 18: Display Sales

SELECT *
FROM SALES
ORDER BY SALE_ID;


// Task 19: Display Staging Row Counts

SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM CUSTOMERS

UNION ALL

SELECT 'PRODUCTS', COUNT(*)
FROM PRODUCTS

UNION ALL

SELECT 'BRANCHES', COUNT(*)
FROM BRANCHES

UNION ALL

SELECT 'CALENDAR', COUNT(*)
FROM CALENDAR

UNION ALL

SELECT 'SALES', COUNT(*)
FROM SALES;


// PHASE 8: CREATE SNOWFLAKE SCHEMA

USE SCHEMA ANALYTICS;


// Task 20: Create Region Dimension

CREATE OR REPLACE TABLE DIM_REGION (
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR(50)
);


// Task 21: Create State Dimension

CREATE OR REPLACE TABLE DIM_STATE (
    STATE_ID NUMBER PRIMARY KEY,
    STATE_NAME VARCHAR(100),
    REGION_ID NUMBER,

    CONSTRAINT FK_STATE_REGION
        FOREIGN KEY (REGION_ID)
        REFERENCES DIM_REGION(REGION_ID)
);


// Task 22: Create City Dimension

CREATE OR REPLACE TABLE DIM_CITY (
    CITY_ID NUMBER PRIMARY KEY,
    CITY_NAME VARCHAR(100),
    STATE_ID NUMBER,

    CONSTRAINT FK_CITY_STATE
        FOREIGN KEY (STATE_ID)
        REFERENCES DIM_STATE(STATE_ID)
);


// Task 23: Create Category Dimension

CREATE OR REPLACE TABLE DIM_CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100)
);


// Task 24: Create Brand Dimension

CREATE OR REPLACE TABLE DIM_BRAND (
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR(100),
    CATEGORY_ID NUMBER,

    CONSTRAINT FK_BRAND_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES DIM_CATEGORY(CATEGORY_ID)
);


// Task 25: Create Year Dimension

CREATE OR REPLACE TABLE DIM_YEAR (
    YEAR_ID NUMBER PRIMARY KEY,
    YEAR_VALUE NUMBER
);


// Task 26: Create Quarter Dimension

CREATE OR REPLACE TABLE DIM_QUARTER (
    QUARTER_ID NUMBER PRIMARY KEY,
    QUARTER_NAME VARCHAR(10),
    YEAR_ID NUMBER,

    CONSTRAINT FK_QUARTER_YEAR
        FOREIGN KEY (YEAR_ID)
        REFERENCES DIM_YEAR(YEAR_ID)
);


// Task 27: Create Month Dimension

CREATE OR REPLACE TABLE DIM_MONTH (
    MONTH_ID NUMBER PRIMARY KEY,
    MONTH_NAME VARCHAR(20),
    QUARTER_ID NUMBER,

    CONSTRAINT FK_MONTH_QUARTER
        FOREIGN KEY (QUARTER_ID)
        REFERENCES DIM_QUARTER(QUARTER_ID)
);


// Task 28: Create Customer Dimension

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY_ID NUMBER,
    MEMBERSHIP VARCHAR(50),

    CONSTRAINT FK_CUSTOMER_CITY
        FOREIGN KEY (CITY_ID)
        REFERENCES DIM_CITY(CITY_ID)
);


// Task 29: Create Product Dimension

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    BRAND_ID NUMBER,
    PRICE NUMBER(12,2),

    CONSTRAINT FK_PRODUCT_BRAND
        FOREIGN KEY (BRAND_ID)
        REFERENCES DIM_BRAND(BRAND_ID)
);


// Task 30: Create Branch Dimension

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR(150),
    CITY_ID NUMBER,
    MANAGER_NAME VARCHAR(100),

    CONSTRAINT FK_BRANCH_CITY
        FOREIGN KEY (CITY_ID)
        REFERENCES DIM_CITY(CITY_ID)
);


// Task 31: Create Date Dimension

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH_ID NUMBER,
    IS_WEEKEND VARCHAR(10),

    CONSTRAINT FK_DATE_MONTH
        FOREIGN KEY (MONTH_ID)
        REFERENCES DIM_MONTH(MONTH_ID)
);


// Task 32: Create Fact Sales Table

CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_SALES_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_SALES_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_SALES_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    CONSTRAINT FK_SALES_DATE
        FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);


// PHASE 9: LOAD LOOKUP DIMENSIONS

// Task 33: Load Region Dimension

INSERT INTO DIM_REGION VALUES
(1,'South'),
(2,'North'),
(3,'West'),
(4,'East');


// Task 34: Load State Dimension

INSERT INTO DIM_STATE VALUES
(1,'Telangana',1),
(2,'Karnataka',1),
(3,'Tamil Nadu',1),
(4,'Kerala',1),
(5,'Andhra Pradesh',1),
(6,'Maharashtra',3),
(7,'Gujarat',3),
(8,'Delhi',2),
(9,'Rajasthan',2),
(10,'Uttar Pradesh',2),
(11,'Bihar',2),
(12,'West Bengal',4),
(13,'Madhya Pradesh',2),
(14,'Chandigarh',2);


// Task 35: Load City Dimension

INSERT INTO DIM_CITY VALUES
(1,'Hyderabad',1),
(2,'Bangalore',2),
(3,'Chennai',3),
(4,'Ahmedabad',7),
(5,'Delhi',8),
(6,'Vijayawada',5),
(7,'Warangal',1),
(8,'Mumbai',6),
(9,'Jaipur',9),
(10,'Kochi',4),
(11,'Visakhapatnam',5),
(12,'Kolkata',12),
(13,'Lucknow',10),
(14,'Coimbatore',3),
(15,'Patna',11),
(16,'Bhopal',13),
(17,'Chandigarh',14),
(18,'Mysore',2),
(19,'Nagpur',6),
(20,'Thiruvananthapuram',4);


// Task 36: Load Category Dimension

INSERT INTO DIM_CATEGORY VALUES
(1,'Electronics'),
(2,'Accessories'),
(3,'Office Equipment'),
(4,'Networking'),
(5,'Storage'),
(6,'Mobile Accessories');


// Task 37: Load Brand Dimension

INSERT INTO DIM_BRAND VALUES
(1,'Dell',1),
(2,'Samsung',1),
(3,'Apple',1),
(4,'LG',1),
(5,'Logitech',2),
(6,'HP',2),
(7,'Sony',2),
(8,'JBL',2),
(9,'Canon',3),
(10,'Epson',3),
(11,'TP-Link',4),
(12,'Cisco',4),
(13,'Seagate',5),
(14,'SanDisk',5),
(15,'Mi',6),
(16,'Anker',6),
(17,'Samsung',5);


// Task 38: Load Year Dimension

INSERT INTO DIM_YEAR VALUES
(1,2026);


// Task 39: Load Quarter Dimension

INSERT INTO DIM_QUARTER VALUES
(1,'Q3',1);


// Task 40: Load Month Dimension

INSERT INTO DIM_MONTH VALUES
(1,'July',1);


// PHASE 10: LOAD NORMALIZED DIMENSIONS

// Task 41: Load Customer Dimension

INSERT INTO DIM_CUSTOMER
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CT.CITY_ID,
    C.MEMBERSHIP
FROM STAGING.CUSTOMERS C
JOIN DIM_CITY CT
    ON C.CITY = CT.CITY_NAME;


// Task 42: Load Product Dimension

INSERT INTO DIM_PRODUCT
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_ID,
    P.PRICE
FROM STAGING.PRODUCTS P
JOIN DIM_BRAND B
    ON P.BRAND = B.BRAND_NAME
JOIN DIM_CATEGORY CAT
    ON P.CATEGORY = CAT.CATEGORY_NAME
    AND B.CATEGORY_ID = CAT.CATEGORY_ID;


// Task 43: Load Branch Dimension

INSERT INTO DIM_BRANCH
SELECT
    BR.BRANCH_ID,
    BR.BRANCH_NAME,
    CT.CITY_ID,
    BR.MANAGER_NAME
FROM STAGING.BRANCHES BR
JOIN DIM_CITY CT
    ON BR.CITY = CT.CITY_NAME;


// Task 44: Load Date Dimension

INSERT INTO DIM_DATE
SELECT
    C.DATE_ID,
    C.DATE,
    C.DAY,
    C.DAY_NAME,
    C.WEEK_NO,
    M.MONTH_ID,
    C.IS_WEEKEND
FROM STAGING.CALENDAR C
JOIN DIM_MONTH M
    ON C.MONTH = M.MONTH_NAME;


// PHASE 11: LOAD FACT TABLE

// Task 45: Load Fact Sales

INSERT INTO FACT_SALES
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
FROM STAGING.SALES;


// PHASE 12: VERIFY FINAL DATA

// Task 46: Display Customer Dimension

SELECT *
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;


// Task 47: Display Product Dimension

SELECT *
FROM DIM_PRODUCT
ORDER BY PRODUCT_ID;


// Task 48: Display Branch Dimension

SELECT *
FROM DIM_BRANCH
ORDER BY BRANCH_ID;


// Task 49: Display Date Dimension

SELECT *
FROM DIM_DATE
ORDER BY DATE_ID;


// Task 50: Display Fact Sales

SELECT *
FROM FACT_SALES
ORDER BY SALE_ID;


// Task 51: Display Final Row Counts

SELECT 'DIM_REGION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM DIM_REGION

UNION ALL

SELECT 'DIM_STATE', COUNT(*)
FROM DIM_STATE

UNION ALL

SELECT 'DIM_CITY', COUNT(*)
FROM DIM_CITY

UNION ALL

SELECT 'DIM_CATEGORY', COUNT(*)
FROM DIM_CATEGORY

UNION ALL

SELECT 'DIM_BRAND', COUNT(*)
FROM DIM_BRAND

UNION ALL

SELECT 'DIM_YEAR', COUNT(*)
FROM DIM_YEAR

UNION ALL

SELECT 'DIM_QUARTER', COUNT(*)
FROM DIM_QUARTER

UNION ALL

SELECT 'DIM_MONTH', COUNT(*)
FROM DIM_MONTH

UNION ALL

SELECT 'DIM_CUSTOMER', COUNT(*)
FROM DIM_CUSTOMER

UNION ALL

SELECT 'DIM_PRODUCT', COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT 'DIM_BRANCH', COUNT(*)
FROM DIM_BRANCH

UNION ALL

SELECT 'DIM_DATE', COUNT(*)
FROM DIM_DATE

UNION ALL

SELECT 'FACT_SALES', COUNT(*)
FROM FACT_SALES;


// PHASE 13: ANALYTICAL REPORTS

// Task 52: Customer-wise Sales Report

SELECT
    C.CUSTOMER_NAME,
    CT.CITY_NAME,
    S.STATE_NAME,
    C.MEMBERSHIP,
    SUM(F.QUANTITY) AS TOTAL_QTY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_CITY CT
    ON C.CITY_ID = CT.CITY_ID
JOIN DIM_STATE S
    ON CT.STATE_ID = S.STATE_ID
GROUP BY
    C.CUSTOMER_NAME,
    CT.CITY_NAME,
    S.STATE_NAME,
    C.MEMBERSHIP
ORDER BY TOTAL_REVENUE DESC;


// Task 53: Product-wise Revenue Report

SELECT
    P.PRODUCT_NAME,
    CAT.CATEGORY_NAME,
    B.BRAND_NAME,
    P.PRICE,
    SUM(F.QUANTITY) AS TOTAL_QTY_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY CAT
    ON B.CATEGORY_ID = CAT.CATEGORY_ID
GROUP BY
    P.PRODUCT_NAME,
    CAT.CATEGORY_NAME,
    B.BRAND_NAME,
    P.PRICE
ORDER BY TOTAL_REVENUE DESC;


// Task 54: Brand-wise Revenue Report

SELECT
    B.BRAND_NAME,
    CAT.CATEGORY_NAME,
    SUM(F.QUANTITY) AS TOTAL_QTY_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY CAT
    ON B.CATEGORY_ID = CAT.CATEGORY_ID
GROUP BY
    B.BRAND_NAME,
    CAT.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;


// Task 55: Category-wise Revenue Report

SELECT
    CAT.CATEGORY_NAME,
    SUM(F.QUANTITY) AS TOTAL_QTY_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    COUNT(*) AS TOTAL_TRANSACTIONS
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY CAT
    ON B.CATEGORY_ID = CAT.CATEGORY_ID
GROUP BY CAT.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;


// Task 56: City-wise Sales Report

SELECT
    CT.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH BR
    ON F.BRANCH_ID = BR.BRANCH_ID
JOIN DIM_CITY CT
    ON BR.CITY_ID = CT.CITY_ID
JOIN DIM_STATE S
    ON CT.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY
    CT.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME
ORDER BY TOTAL_REVENUE DESC;


// Task 57: State-wise Revenue Report

SELECT
    S.STATE_NAME,
    R.REGION_NAME,
    SUM(F.QUANTITY) AS TOTAL_QTY_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH BR
    ON F.BRANCH_ID = BR.BRANCH_ID
JOIN DIM_CITY CT
    ON BR.CITY_ID = CT.CITY_ID
JOIN DIM_STATE S
    ON CT.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY
    S.STATE_NAME,
    R.REGION_NAME
ORDER BY TOTAL_REVENUE DESC;


// Task 58: Region-wise Revenue Report

SELECT
    R.REGION_NAME,
    COUNT(DISTINCT BR.BRANCH_ID) AS NUM_BRANCHES,
    SUM(F.QUANTITY) AS TOTAL_QTY_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    ROUND(AVG(F.TOTAL_AMOUNT),2) AS AVG_SALE_AMOUNT
FROM FACT_SALES F
JOIN DIM_BRANCH BR
    ON F.BRANCH_ID = BR.BRANCH_ID
JOIN DIM_CITY CT
    ON BR.CITY_ID = CT.CITY_ID
JOIN DIM_STATE S
    ON CT.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY R.REGION_NAME
ORDER BY TOTAL_REVENUE DESC;


// Task 59: Monthly Revenue Report

SELECT
    M.MONTH_NAME,
    Q.QUARTER_NAME,
    Y.YEAR_VALUE,
    SUM(F.TOTAL_AMOUNT) AS MONTHLY_REVENUE,
    SUM(F.QUANTITY) AS TOTAL_QTY_SOLD
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
JOIN DIM_MONTH M
    ON D.MONTH_ID = M.MONTH_ID
JOIN DIM_QUARTER Q
    ON M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON Q.YEAR_ID = Y.YEAR_ID
GROUP BY
    M.MONTH_NAME,
    Q.QUARTER_NAME,
    Y.YEAR_VALUE
ORDER BY
    Y.YEAR_VALUE,
    M.MONTH_NAME;


// Task 60: Quarterly Revenue Report

SELECT
    Q.QUARTER_NAME,
    Y.YEAR_VALUE,
    SUM(F.TOTAL_AMOUNT) AS QUARTERLY_REVENUE,
    SUM(F.QUANTITY) AS TOTAL_QTY_SOLD
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
JOIN DIM_MONTH M
    ON D.MONTH_ID = M.MONTH_ID
JOIN DIM_QUARTER Q
    ON M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON Q.YEAR_ID = Y.YEAR_ID
GROUP BY
    Q.QUARTER_NAME,
    Y.YEAR_VALUE
ORDER BY
    Y.YEAR_VALUE,
    Q.QUARTER_NAME;


// Task 61: Top 10 Customers

SELECT
    C.CUSTOMER_NAME,
    CT.CITY_NAME,
    C.MEMBERSHIP,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_CITY CT
    ON C.CITY_ID = CT.CITY_ID
GROUP BY
    C.CUSTOMER_NAME,
    CT.CITY_NAME,
    C.MEMBERSHIP
ORDER BY TOTAL_SPENT DESC
LIMIT 10;


// Task 62: Top 10 Products

SELECT
    P.PRODUCT_NAME,
    CAT.CATEGORY_NAME,
    B.BRAND_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY CAT
    ON B.CATEGORY_ID = CAT.CATEGORY_ID
GROUP BY
    P.PRODUCT_NAME,
    CAT.CATEGORY_NAME,
    B.BRAND_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


// Task 63: Top 10 Branches

SELECT
    BR.BRANCH_NAME,
    CT.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH BR
    ON F.BRANCH_ID = BR.BRANCH_ID
JOIN DIM_CITY CT
    ON BR.CITY_ID = CT.CITY_ID
JOIN DIM_STATE S
    ON CT.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY
    BR.BRANCH_NAME,
    CT.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


// Task 64: Customer Purchase Trend

SELECT
    C.CUSTOMER_NAME,
    M.MONTH_NAME,
    Y.YEAR_VALUE,
    SUM(F.TOTAL_AMOUNT) AS MONTHLY_SPEND
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
JOIN DIM_MONTH M
    ON D.MONTH_ID = M.MONTH_ID
JOIN DIM_QUARTER Q
    ON M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON Q.YEAR_ID = Y.YEAR_ID
GROUP BY
    C.CUSTOMER_NAME,
    M.MONTH_NAME,
    Y.YEAR_VALUE
ORDER BY
    C.CUSTOMER_NAME,
    Y.YEAR_VALUE;


// Task 65: Product Performance Report

SELECT
    P.PRODUCT_NAME,
    CAT.CATEGORY_NAME,
    B.BRAND_NAME,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REVENUE,
    ROUND(AVG(F.TOTAL_AMOUNT),2) AS AVG_SALE_VALUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY CAT
    ON B.CATEGORY_ID = CAT.CATEGORY_ID
GROUP BY
    P.PRODUCT_NAME,
    CAT.CATEGORY_NAME,
    B.BRAND_NAME
ORDER BY REVENUE DESC;


// Task 66: Regional Sales Dashboard

SELECT
    R.REGION_NAME,
    S.STATE_NAME,
    CT.CITY_NAME,
    BR.BRANCH_NAME,
    BR.MANAGER_NAME,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH BR
    ON F.BRANCH_ID = BR.BRANCH_ID
JOIN DIM_CITY CT
    ON BR.CITY_ID = CT.CITY_ID
JOIN DIM_STATE S
    ON CT.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY
    R.REGION_NAME,
    S.STATE_NAME,
    CT.CITY_NAME,
    BR.BRANCH_NAME,
    BR.MANAGER_NAME
ORDER BY
    R.REGION_NAME,
    REVENUE DESC;


// PHASE 14: DATA VALIDATION

// Task 67: Check Customer Orphans

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;


// Task 68: Check Product Orphans

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;


// Task 69: Check Branch Orphans

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
WHERE B.BRANCH_ID IS NULL;


// Task 70: Check Date Orphans

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
WHERE D.DATE_ID IS NULL;


// Task 71: Display Analytics Tables

SHOW TABLES IN SCHEMA RETAIL_SNOWFLAKE_DW.ANALYTICS;


// Task 72: Display Staging Tables

SHOW TABLES IN SCHEMA RETAIL_SNOWFLAKE_DW.STAGING;


// Task 73: Display Stage Files

LIST @RETAIL_SNOWFLAKE_DW.STAGING.RETAIL_CSV_STAGE;